server:
  port: 8087

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/realm-for-dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

application:
  jwt:
    secret:
      key: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret

management:
  tracing:
    sampling:
      probability: 1.0
