server:
  port: 8082

spring:
  application:
    name: category
  r2dbc:
    url: r2dbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/hs_category
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

application:
  jwt:
    secretKey: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 1
    internal:
      username: yelan
      roleName: ROLE_USER
