server:
  port: 8083

spring:
  application:
    name: consumption
  r2dbc:
    url: r2dbc:mysql://localhost:3306/hs_consumption?serverTimezone=America/Lima
    username: root
    password: BBDDlocal361

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
