server:
  port: 8081

spring:
  application:
    name: nourishment
  r2dbc:
    url: r2dbc:mysql://localhost:3306/hs_nourishment?serverTimezone=UTC
    username: root
    password: BBDDlocal361

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
