server:
  port: 8084

spring:
  application:
    name: role
  r2dbc:
    url: r2dbc:mysql://localhost:3306/hs_role?serverTimezone=America/Lima
    username: root
    password: BBDDlocal361

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
