server:
  port: 8080

spring:
  application:
    name: user
  r2dbc:
    url: r2dbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/hs_user
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    webclient:
      enable: true

application:
  jwt:
    secretKey: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 1
    internal:
      username: yelan
      roleName: ROLE_USER
